apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.name }}
  annotations:
    crossplane.io/external-name: {{ .Values.name }}
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    atombank.co/bucket-name: {{ .Values.name }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  forProvider:
    location: {{ .Values.location }}
    storageClass: {{ .Values.storageClass }}
  deletionPolicy: {{ .Values.deletionPolicy }}
