{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deployment.serviceAccountName" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
  
  annotations:
  {{- if .Values.serviceAccount.workloadIdentity }}
    iam.gke.io/gcp-service-account: {{ include "deployment.serviceAccountName" . }}@{{ .Values.global.projectId }}.iam.gserviceaccount.com
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
