apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  labels:
    atombank.co/name: {{ .Values.name }}
  annotations: 
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.name }}
spec:
  forProvider:
    member: "serviceAccount:{{ .Values.global.projectId }}.svc.id.goog[{{ .Release.Namespace }}/{{ .Values.name }}]"
    role: roles/iam.workloadIdentityUser
    serviceAccountIdSelector:
      matchLabels:
        atombank.co/name: {{ .Values.name }}