apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  annotations: 
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    name: {{ .Values.name }}
spec:
  forProvider:
    displayName: {{ .Values.name }}
